sudo: false
language: c++
notifications:
 slack: wavm:XJj5kD0mDa4FMKLUz9laRC48

# Build configuration matrix

compiler:
 - clang
 - gcc

env:
 - ENABLE_RUNTIME=NO  ENABLE_STATIC_LINKING=NO  ENABLE_RELEASE_ASSERTS=NO  ENABLE_ASAN=NO  ENABLE_UBSAN=NO  USE_LIBFUZZER=NO
 - ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO  ENABLE_RELEASE_ASSERTS=NO  ENABLE_ASAN=NO  ENABLE_UBSAN=NO  USE_LIBFUZZER=NO
 - ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=YES ENABLE_RELEASE_ASSERTS=NO  ENABLE_ASAN=NO  ENABLE_UBSAN=NO  USE_LIBFUZZER=NO
 - ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO  ENABLE_RELEASE_ASSERTS=YES ENABLE_ASAN=NO  ENABLE_UBSAN=NO  USE_LIBFUZZER=NO
 - ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO  ENABLE_RELEASE_ASSERTS=NO  ENABLE_ASAN=YES ENABLE_UBSAN=NO  USE_LIBFUZZER=NO
 - ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO  ENABLE_RELEASE_ASSERTS=NO  ENABLE_ASAN=NO  ENABLE_UBSAN=YES USE_LIBFUZZER=NO
 - ENABLE_RUNTIME=YES ENABLE_STATIC_LINKING=NO  ENABLE_RELEASE_ASSERTS=YES ENABLE_ASAN=YES ENABLE_UBSAN=YES USE_LIBFUZZER=YES

os:
 - linux
 - osx
 
matrix:
  exclude:
    - os: osx
      compiler: gcc

# OSX configuration
osx_image: xcode9.3beta

# Linux configuration
addons:
 apt:
  sources:
   - llvm-toolchain-trusty-5.0
   - ubuntu-toolchain-r-test
  packages:
   - gcc-7
   - g++-7
   - libedit-dev
   - clang-5.0

# Defer the actual build script to travis-build.sh
script: ./travis-build.sh
